language: node_js
node_js:
  - 13

services:
  - docker

# Pre-testing installs

# Scripts to be run such as tests
before_script:
  - echo "no tests"

script:
  - docker --version # print the version for logging
  - docker build -t rev-proxy .
  - docker tag rev-proxy scharati/rev-proxy:localdocker

after_success:
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
  - docker push scharati/rev-proxy

